services:
  imageforge:
    build:
      context: .
    container_name: imageforge
    restart: unless-stopped
    environment:
      HOST: "0.0.0.0"
      IMAGEFORGE_API_KEY: ${IMAGEFORGE_API_KEY:-}
      IMAGEFORGE_API_ENDPOINTS: ${IMAGEFORGE_API_ENDPOINTS:-}
      PORT: "8080"
    ports:
      - "5173:8080"
